<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Screenshot</AssemblyName>
    <RootNamespace>Screenshot.Desktop</RootNamespace>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Screenshot.Core\Screenshot.Core.csproj" />
  </ItemGroup>
</Project>
